### ISSUE TITLE
Request to add 2 additional OU levels

### ISSUE THREAD

**Issue by atqhg23** [infrablocks/terraform-aws-organization#67]
Can 2 additional OU levels be added? 

Reviewing the AWS Organizations service quotas, "five levels of OUs deep under a root" are allowed. Link to quotas - https://docs.aws.amazon.com/organizations/latest/userguide/orgs_reference_limits.html

**Comment by jonassvalin** [comment]
@atqhg23 I'm currently working on the indexing PR, but may be able to look into this after. Can't give an exact timeline though.

Thanks,
Jonas

**Comment by jonassvalin** [comment]
Hi @atqhg23 
Thanks for the issue. I've incorporated some of these ideas in a separate release candidate that has just gone out as [2.0.0-rc.4](https://registry.terraform.io/modules/infrablocks/organization/aws/2.0.0-rc.4). Could you please try it out and see if it works as you expect, and if so I'll publish the full release.

Since this change modifies the state, you will have to manually edit the state file if upgrading from 1.x.x. If you need guidance on this, please create an issue. It's fairly straight forward if you're comfortable with Terraform state.

Cheers
@jonassvalin
